shellcheck errors fixed

diff --git a/.github/workflows/test-action-checkout.yml b/.github/workflows/test-action-checkout.yml
--- a/.github/workflows/test-action-checkout.yml
+++ b/.github/workflows/test-action-checkout.yml
@@ -24,10 +24,13 @@ jobs:
       - uses: ./action-templates/actions/action-checkout
       - name: persist-credentials-default
         run: |
-          if [ -e "$RUNNER_TEMP"/git-credentials-*.config ]; then
-            echo "Detected credential file"
-            exit 1
-          fi
+          for file in "$RUNNER_TEMP"/git-credentials-*.config
+          do
+            if [ -e "$file" ]; then
+              echo "Detected credential file"
+              exit 1
+            fi
+          done
 
   test-checkout-persist-credentials-false:
     name: test-persist-credentials-false
@@ -43,10 +46,13 @@ jobs:
           persist-credentials: false
       - name: persist-credentials-false
         run: |
-          if [ -e "$RUNNER_TEMP"/git-credentials-*.config ]; then
-            echo "Detected credential file"
-            exit 1
-          fi
+          for file in "$RUNNER_TEMP"/git-credentials-*.config
+          do
+            if [ -e "$file" ]; then
+              echo "Detected credential file"
+              exit 1
+            fi
+          done
 
   test-checkout-persist-credentials-true:
     name: test-persist-credentials-true
@@ -62,7 +68,10 @@ jobs:
           persist-credentials: true
       - name: persist-credentials-true
         run: |
-          if [ ! -e "$RUNNER_TEMP"/git-credentials-*.config ]; then
-            echo "Couldn't detect credential file"
-            exit 1
-          fi
+          for file in "$RUNNER_TEMP"/git-credentials-*.config
+          do
+            if [ ! -e "$file" ]; then
+              echo "Couldn't detect credential file"
+              exit 1
+            fi
+          done
